import type { Metadata } from "next";
import { Ubuntu, Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const rubik = Ubuntu({
  style: "normal",
  weight: ["400", "500", "700"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rubik.className}>
      <head />
      <body>
        <main className="bg-black/[0.96] antialiased bg-grid-white/[0.02] min-h-screen flex items-center justify-center px-2">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
