import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        <main className="bg-gradient-to-tl from-yellow-200 to-red-400 min-h-screen flex items-center justify-center px-2">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
